export const copy = {
  app: {
    nome: "Bubu",
    nomeHeader: "APP Bubu",
    tagline: "As contas da casa, do nosso jeito.",
  },
  auth: {
    titulo: "Entrar no Bubu",
    subtitulo: "Entra com seu e-mail e senha.",
    email: { label: "E-mail", placeholder: "voce@email.com" },
    senha: { label: "Senha", placeholder: "sua senha" },
    nome: { label: "Nome", placeholder: "Seu nome" },
    entrar: "Entrar",
    criar: "Criar conta",
    entrando: "Entrando...",
    confirmaEmail: "Conta criada. Confirma teu e-mail pra entrar.",
    emailNaoConfirmado: "Falta confirmar teu e-mail. Procura o link na caixa de entrada (ou no spam).",
    demoAviso: "(Modo demo — qualquer e-mail/senha funciona)",
    erroLogin: "E-mail ou senha errado. Confere aí.",
    erroGeral: "Algo travou no login. Tenta de novo?",
  },
  home: {
    mesReferenciaLabel: "MÊS REFERÊNCIA",
    totalAPagar: "TOTAL A PAGAR",
    pagos: "PAGOS",
    total: "TOTAL",
    mesAnterior: "Mês anterior",
    proximoMes: "Próximo mês",
    tudoPago: "Tudo pago esse mês. Pode respirar.",
  },
  vazio: {
    titulo: "Nenhuma conta por aqui ainda.",
    texto: "Toca no + pra adicionar a primeira.",
    botao: "Adicionar conta",
  },
  billCard: {
    vence: "Vence: {data}",
    parcela: "{atual}/{total}",
    statusAPagar: "A PAGAR",
    statusPago: "PAGO",
    statusAtrasado: "ATRASADO",
  },
  conta: {
    marcarPago: "Marcar como pago",
    desfazer: "Desfazer pagamento",
    parcela: "Parcela {atual} de {total}",
    editar: "Editar",
    apagar: "Apagar",
    transferir: "Transferir para o próximo mês",
    pagoPor: "Pago por {nome}",
    fechar: "Fechar",
  },
  comprovante: {
    titulo: "Comprovante",
    enviar: "Enviar comprovante",
    enviando: "Enviando...",
    enviado: "Comprovante salvo.",
    ver: "Ver comprovante",
    erro: "Não consegui subir o arquivo. Tenta de novo?",
    somenteOnline: "Comprovantes ficam disponíveis com o Supabase conectado.",
  },
  formulario: {
    novoTitulo: "Nova conta",
    editarTitulo: "Editar conta",
    nome: { label: "Nome", placeholder: "Ex: Luz, Internet, Aluguel" },
    valor: { label: "Valor", placeholder: "R$ 0,00" },
    vencimento: { label: "Vence todo dia", placeholder: "10" },
    categoria: { label: "Categoria" },
    tipo: {
      label: "Tipo",
      mensal: "Todo mês",
      anual: "Uma vez por ano",
      parcelada: "Parcelada",
    },
    anualAjuda: "Tipo IPTU e IPVA, que caem uma vez no ano.",
    parcelasLabel: "Quantas parcelas no total",
    parcelasPlaceholder: "10",
    parcelaAtualLabel: "Em qual parcela vocês estão",
    parcelaAtualPlaceholder: "1",
    parcelaAjuda: "Se a conta já vem de outros meses, informa a parcela deste mês. Ela avança sozinha e some depois da última.",
    parcelaAtualInvalida: "A parcela atual não pode ser maior que o total.",
    salvar: "Salvar",
    cancelar: "Cancelar",
    faltaNome: "Dá um nome pra conta.",
    valorInvalido: "Põe um valor válido.",
    vencimentoInvalido: "Dia de vencimento inválido.",
  },
  excluir: {
    titulo: "Apagar essa conta?",
    texto: "Não dá pra voltar atrás.",
    confirmar: "Apagar",
    cancelar: "Deixa quieto",
  },
  contas: {
    titulo: "Contas da casa",
    subtitulo: "As contas fixas que se repetem todo mês.",
    parcelaInfo: "parcela {atual} de {total}",
    encerrada: "encerrada",
  },
  relatorios: {
    titulo: "Relatórios",
    subtitulo: "Como foram os meses até aqui.",
    pago: "Pago",
    pendente: "Em aberto",
    total: "Total",
    porCategoria: "Por categoria",
    vazio: "Ainda não tem histórico. Volta depois do primeiro mês.",
  },
  config: {
    titulo: "Configurações",
    casaTitulo: "A casa de vocês",
    convidarTexto: "Manda esse código pra quem divide as contas com você.",
    copiar: "Copiar código",
    copiado: "Copiado.",
    membros: "Quem tá na casa",
    voce: "você",
    dono: "dono da casa",
    addTitulo: "Adicionar participante",
    addNomePlaceholder: "Nome de quem divide com você",
    addBotao: "Adicionar",
    addAjudaOnline: "A pessoa cria a conta dela no Bubu e entra com o código da casa acima.",
    addFeito: "Participante adicionado.",
    remover: "Remover {nome} da casa",
    removerConfirma: "Remover?",
    removido: "Participante removido.",
    removerErro: "Não consegui remover. Só o dono da casa pode fazer isso.",
    entrarTitulo: "Tem um código?",
    entrarTexto: "Cola aqui pra entrar na mesma casa.",
    entrarBotao: "Entrar na casa",
    codigoInvalido: "Esse código não existe. Confere com a pessoa.",
    sair: "Sair da conta",
    modoDemo: "Rodando em modo demo (sem Supabase). Os dados ficam só neste aparelho.",
    modoOnline: "Conectado ao Supabase.",
  },
  offline: {
    banner: "Sem internet agora. Tá tudo salvo, sincroniza quando voltar.",
    voltou: "Voltou. Já sincronizei tudo.",
  },
  toast: {
    salvo: "Conta salva.",
    pago: "Marcado como pago.",
    editado: "Pronto, atualizei.",
    apagado: "Apaguei a conta.",
    erro: "Não rolou. Tenta de novo?",
    transferido: "Transferida pro mês que vem.",
  },
  nav: {
    inicio: "Início",
    contas: "Contas",
    relatorios: "Relatórios",
    configuracoes: "Configurações",
  },
  meses: [
    "Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho",
    "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro",
  ],
}
